package com.atlchain.bcgis.data.protoBuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GeoData.proto

public final class GeoDataOuterClass {
  private GeoDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PropOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Prop)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code Prop}
   */
  public  static final class Prop extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Prop)
      PropOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Prop.newBuilder() to construct.
    private Prop(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Prop() {
      key_ = "";
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Prop(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GeoDataOuterClass.internal_static_Prop_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GeoDataOuterClass.internal_static_Prop_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GeoDataOuterClass.Prop.class, GeoDataOuterClass.Prop.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GeoDataOuterClass.Prop)) {
        return super.equals(obj);
      }
      GeoDataOuterClass.Prop other = (GeoDataOuterClass.Prop) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GeoDataOuterClass.Prop parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GeoDataOuterClass.Prop parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GeoDataOuterClass.Prop parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GeoDataOuterClass.Prop parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GeoDataOuterClass.Prop parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GeoDataOuterClass.Prop parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GeoDataOuterClass.Prop parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GeoDataOuterClass.Prop parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GeoDataOuterClass.Prop parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GeoDataOuterClass.Prop parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GeoDataOuterClass.Prop parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GeoDataOuterClass.Prop parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GeoDataOuterClass.Prop prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Prop}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Prop)
        GeoDataOuterClass.PropOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GeoDataOuterClass.internal_static_Prop_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GeoDataOuterClass.internal_static_Prop_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GeoDataOuterClass.Prop.class, GeoDataOuterClass.Prop.Builder.class);
      }

      // Construct using GeoDataOuterClass.Prop.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        key_ = "";

        value_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GeoDataOuterClass.internal_static_Prop_descriptor;
      }

      @java.lang.Override
      public GeoDataOuterClass.Prop getDefaultInstanceForType() {
        return GeoDataOuterClass.Prop.getDefaultInstance();
      }

      @java.lang.Override
      public GeoDataOuterClass.Prop build() {
        GeoDataOuterClass.Prop result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GeoDataOuterClass.Prop buildPartial() {
        GeoDataOuterClass.Prop result = new GeoDataOuterClass.Prop(this);
        result.key_ = key_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GeoDataOuterClass.Prop) {
          return mergeFrom((GeoDataOuterClass.Prop)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GeoDataOuterClass.Prop other) {
        if (other == GeoDataOuterClass.Prop.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GeoDataOuterClass.Prop parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GeoDataOuterClass.Prop) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Prop)
    }

    // @@protoc_insertion_point(class_scope:Prop)
    private static final GeoDataOuterClass.Prop DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GeoDataOuterClass.Prop();
    }

    public static GeoDataOuterClass.Prop getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Prop>
        PARSER = new com.google.protobuf.AbstractParser<Prop>() {
      @java.lang.Override
      public Prop parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Prop(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Prop> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Prop> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GeoDataOuterClass.Prop getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GeoDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GeoData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes geometry = 1;</code>
     */
    com.google.protobuf.ByteString getGeometry();

    /**
     * <code>repeated .Prop prop = 2;</code>
     */
    java.util.List<GeoDataOuterClass.Prop> 
        getPropList();
    /**
     * <code>repeated .Prop prop = 2;</code>
     */
    GeoDataOuterClass.Prop getProp(int index);
    /**
     * <code>repeated .Prop prop = 2;</code>
     */
    int getPropCount();
    /**
     * <code>repeated .Prop prop = 2;</code>
     */
    java.util.List<? extends GeoDataOuterClass.PropOrBuilder> 
        getPropOrBuilderList();
    /**
     * <code>repeated .Prop prop = 2;</code>
     */
    GeoDataOuterClass.PropOrBuilder getPropOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GeoData}
   */
  public  static final class GeoData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GeoData)
      GeoDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GeoData.newBuilder() to construct.
    private GeoData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GeoData() {
      geometry_ = com.google.protobuf.ByteString.EMPTY;
      prop_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GeoData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              geometry_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                prop_ = new java.util.ArrayList<GeoDataOuterClass.Prop>();
                mutable_bitField0_ |= 0x00000002;
              }
              prop_.add(
                  input.readMessage(GeoDataOuterClass.Prop.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          prop_ = java.util.Collections.unmodifiableList(prop_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GeoDataOuterClass.internal_static_GeoData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GeoDataOuterClass.internal_static_GeoData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GeoDataOuterClass.GeoData.class, GeoDataOuterClass.GeoData.Builder.class);
    }

    private int bitField0_;
    public static final int GEOMETRY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString geometry_;
    /**
     * <code>bytes geometry = 1;</code>
     */
    public com.google.protobuf.ByteString getGeometry() {
      return geometry_;
    }

    public static final int PROP_FIELD_NUMBER = 2;
    private java.util.List<GeoDataOuterClass.Prop> prop_;
    /**
     * <code>repeated .Prop prop = 2;</code>
     */
    public java.util.List<GeoDataOuterClass.Prop> getPropList() {
      return prop_;
    }
    /**
     * <code>repeated .Prop prop = 2;</code>
     */
    public java.util.List<? extends GeoDataOuterClass.PropOrBuilder> 
        getPropOrBuilderList() {
      return prop_;
    }
    /**
     * <code>repeated .Prop prop = 2;</code>
     */
    public int getPropCount() {
      return prop_.size();
    }
    /**
     * <code>repeated .Prop prop = 2;</code>
     */
    public GeoDataOuterClass.Prop getProp(int index) {
      return prop_.get(index);
    }
    /**
     * <code>repeated .Prop prop = 2;</code>
     */
    public GeoDataOuterClass.PropOrBuilder getPropOrBuilder(
        int index) {
      return prop_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!geometry_.isEmpty()) {
        output.writeBytes(1, geometry_);
      }
      for (int i = 0; i < prop_.size(); i++) {
        output.writeMessage(2, prop_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!geometry_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, geometry_);
      }
      for (int i = 0; i < prop_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, prop_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GeoDataOuterClass.GeoData)) {
        return super.equals(obj);
      }
      GeoDataOuterClass.GeoData other = (GeoDataOuterClass.GeoData) obj;

      if (!getGeometry()
          .equals(other.getGeometry())) return false;
      if (!getPropList()
          .equals(other.getPropList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GEOMETRY_FIELD_NUMBER;
      hash = (53 * hash) + getGeometry().hashCode();
      if (getPropCount() > 0) {
        hash = (37 * hash) + PROP_FIELD_NUMBER;
        hash = (53 * hash) + getPropList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GeoDataOuterClass.GeoData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GeoDataOuterClass.GeoData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GeoDataOuterClass.GeoData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GeoDataOuterClass.GeoData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GeoDataOuterClass.GeoData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GeoDataOuterClass.GeoData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GeoDataOuterClass.GeoData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GeoDataOuterClass.GeoData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GeoDataOuterClass.GeoData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GeoDataOuterClass.GeoData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GeoDataOuterClass.GeoData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GeoDataOuterClass.GeoData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GeoDataOuterClass.GeoData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GeoData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GeoData)
        GeoDataOuterClass.GeoDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GeoDataOuterClass.internal_static_GeoData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GeoDataOuterClass.internal_static_GeoData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GeoDataOuterClass.GeoData.class, GeoDataOuterClass.GeoData.Builder.class);
      }

      // Construct using GeoDataOuterClass.GeoData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPropFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        geometry_ = com.google.protobuf.ByteString.EMPTY;

        if (propBuilder_ == null) {
          prop_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          propBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GeoDataOuterClass.internal_static_GeoData_descriptor;
      }

      @java.lang.Override
      public GeoDataOuterClass.GeoData getDefaultInstanceForType() {
        return GeoDataOuterClass.GeoData.getDefaultInstance();
      }

      @java.lang.Override
      public GeoDataOuterClass.GeoData build() {
        GeoDataOuterClass.GeoData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GeoDataOuterClass.GeoData buildPartial() {
        GeoDataOuterClass.GeoData result = new GeoDataOuterClass.GeoData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.geometry_ = geometry_;
        if (propBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            prop_ = java.util.Collections.unmodifiableList(prop_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.prop_ = prop_;
        } else {
          result.prop_ = propBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GeoDataOuterClass.GeoData) {
          return mergeFrom((GeoDataOuterClass.GeoData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GeoDataOuterClass.GeoData other) {
        if (other == GeoDataOuterClass.GeoData.getDefaultInstance()) return this;
        if (other.getGeometry() != com.google.protobuf.ByteString.EMPTY) {
          setGeometry(other.getGeometry());
        }
        if (propBuilder_ == null) {
          if (!other.prop_.isEmpty()) {
            if (prop_.isEmpty()) {
              prop_ = other.prop_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePropIsMutable();
              prop_.addAll(other.prop_);
            }
            onChanged();
          }
        } else {
          if (!other.prop_.isEmpty()) {
            if (propBuilder_.isEmpty()) {
              propBuilder_.dispose();
              propBuilder_ = null;
              prop_ = other.prop_;
              bitField0_ = (bitField0_ & ~0x00000002);
              propBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPropFieldBuilder() : null;
            } else {
              propBuilder_.addAllMessages(other.prop_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GeoDataOuterClass.GeoData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GeoDataOuterClass.GeoData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString geometry_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes geometry = 1;</code>
       */
      public com.google.protobuf.ByteString getGeometry() {
        return geometry_;
      }
      /**
       * <code>bytes geometry = 1;</code>
       */
      public Builder setGeometry(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        geometry_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes geometry = 1;</code>
       */
      public Builder clearGeometry() {
        
        geometry_ = getDefaultInstance().getGeometry();
        onChanged();
        return this;
      }

      private java.util.List<GeoDataOuterClass.Prop> prop_ =
        java.util.Collections.emptyList();
      private void ensurePropIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          prop_ = new java.util.ArrayList<GeoDataOuterClass.Prop>(prop_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GeoDataOuterClass.Prop, GeoDataOuterClass.Prop.Builder, GeoDataOuterClass.PropOrBuilder> propBuilder_;

      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public java.util.List<GeoDataOuterClass.Prop> getPropList() {
        if (propBuilder_ == null) {
          return java.util.Collections.unmodifiableList(prop_);
        } else {
          return propBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public int getPropCount() {
        if (propBuilder_ == null) {
          return prop_.size();
        } else {
          return propBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public GeoDataOuterClass.Prop getProp(int index) {
        if (propBuilder_ == null) {
          return prop_.get(index);
        } else {
          return propBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public Builder setProp(
          int index, GeoDataOuterClass.Prop value) {
        if (propBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropIsMutable();
          prop_.set(index, value);
          onChanged();
        } else {
          propBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public Builder setProp(
          int index, GeoDataOuterClass.Prop.Builder builderForValue) {
        if (propBuilder_ == null) {
          ensurePropIsMutable();
          prop_.set(index, builderForValue.build());
          onChanged();
        } else {
          propBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public Builder addProp(GeoDataOuterClass.Prop value) {
        if (propBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropIsMutable();
          prop_.add(value);
          onChanged();
        } else {
          propBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public Builder addProp(
          int index, GeoDataOuterClass.Prop value) {
        if (propBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropIsMutable();
          prop_.add(index, value);
          onChanged();
        } else {
          propBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public Builder addProp(
          GeoDataOuterClass.Prop.Builder builderForValue) {
        if (propBuilder_ == null) {
          ensurePropIsMutable();
          prop_.add(builderForValue.build());
          onChanged();
        } else {
          propBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public Builder addProp(
          int index, GeoDataOuterClass.Prop.Builder builderForValue) {
        if (propBuilder_ == null) {
          ensurePropIsMutable();
          prop_.add(index, builderForValue.build());
          onChanged();
        } else {
          propBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public Builder addAllProp(
          java.lang.Iterable<? extends GeoDataOuterClass.Prop> values) {
        if (propBuilder_ == null) {
          ensurePropIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, prop_);
          onChanged();
        } else {
          propBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public Builder clearProp() {
        if (propBuilder_ == null) {
          prop_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          propBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public Builder removeProp(int index) {
        if (propBuilder_ == null) {
          ensurePropIsMutable();
          prop_.remove(index);
          onChanged();
        } else {
          propBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public GeoDataOuterClass.Prop.Builder getPropBuilder(
          int index) {
        return getPropFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public GeoDataOuterClass.PropOrBuilder getPropOrBuilder(
          int index) {
        if (propBuilder_ == null) {
          return prop_.get(index);  } else {
          return propBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public java.util.List<? extends GeoDataOuterClass.PropOrBuilder> 
           getPropOrBuilderList() {
        if (propBuilder_ != null) {
          return propBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(prop_);
        }
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public GeoDataOuterClass.Prop.Builder addPropBuilder() {
        return getPropFieldBuilder().addBuilder(
            GeoDataOuterClass.Prop.getDefaultInstance());
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public GeoDataOuterClass.Prop.Builder addPropBuilder(
          int index) {
        return getPropFieldBuilder().addBuilder(
            index, GeoDataOuterClass.Prop.getDefaultInstance());
      }
      /**
       * <code>repeated .Prop prop = 2;</code>
       */
      public java.util.List<GeoDataOuterClass.Prop.Builder> 
           getPropBuilderList() {
        return getPropFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GeoDataOuterClass.Prop, GeoDataOuterClass.Prop.Builder, GeoDataOuterClass.PropOrBuilder> 
          getPropFieldBuilder() {
        if (propBuilder_ == null) {
          propBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GeoDataOuterClass.Prop, GeoDataOuterClass.Prop.Builder, GeoDataOuterClass.PropOrBuilder>(
                  prop_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          prop_ = null;
        }
        return propBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GeoData)
    }

    // @@protoc_insertion_point(class_scope:GeoData)
    private static final GeoDataOuterClass.GeoData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GeoDataOuterClass.GeoData();
    }

    public static GeoDataOuterClass.GeoData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GeoData>
        PARSER = new com.google.protobuf.AbstractParser<GeoData>() {
      @java.lang.Override
      public GeoData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GeoData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GeoData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GeoData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GeoDataOuterClass.GeoData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Prop_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Prop_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GeoData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GeoData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rGeoData.proto\"\"\n\004Prop\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\t\"0\n\007GeoData\022\020\n\010geometry\030\001 \001(\014" +
      "\022\023\n\004prop\030\002 \003(\0132\005.Propb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Prop_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Prop_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Prop_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GeoData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GeoData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GeoData_descriptor,
        new java.lang.String[] { "Geometry", "Prop", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
